/**
 * MCP server — the surface OKX.AI actually calls.
 *
 * A2MCP means what it says: the listed endpoint has to speak the Model Context
 * Protocol, not merely be an HTTP API that returns something. Our first listing
 * was rejected for exactly this — the platform opened a session, waited for a
 * stream, got a plain JSON error back, and timed out. A REST 400 is not a
 * protocol error to an MCP client; it is silence.
 *
 * This implements the Streamable HTTP transport: one POST carrying a JSON-RPC
 * message, answered either as an SSE frame (when the caller accepts
 * text/event-stream, which is what the platform does) or as plain JSON.
 *
 * The REST routes in service.js stay as they are — they are the human-facing
 * way in, and the demo records against them.
 */

import { render, renderReading, PATTERN_NAMES, PALETTE_NAMES } from './index.js';
import { toPng } from './raster.js';
import { latestBlock } from './chain.js';

/** Protocol revisions we can speak. We echo the caller's if we know it. */
const SUPPORTED_PROTOCOLS = ['2025-06-18', '2025-03-26', '2024-11-05'];
const DEFAULT_PROTOCOL = '2024-11-05';

const SERVER_INFO = { name: 'ebru', version: '0.1.0' };

/**
 * The largest sheet whose reply still fits down the wire.
 *
 * A tool result carries the image inline as base64, which costs a third again
 * on top of the PNG, and the platform refuses a response over 4.5 MB. The
 * densest pattern measures 3.46 MB at 1200 and 4.52 MB at 1400, so 1200 is the
 * last size that fits with room to spare. It matters more here than it looks:
 * the payment middleware settles *before* it flushes, so a reply that the
 * platform then refuses would leave the caller charged and empty-handed. The
 * REST endpoint streams the PNG itself and is not affected — it still goes to
 * 2000.
 */
const MCP_MAX_SIZE = 1200;

const TOOLS = [
  {
    name: 'marble',
    description:
      'Turn any string into an original Turkish ebru marbled artwork. Computed from the mechanics of the craft, not generated by a model, so the same seed always returns the same artwork. Returns a PNG image.',
    inputSchema: {
      type: 'object',
      properties: {
        seed: {
          type: 'string',
          description: 'Any string — a word, a phrase, a wallet address, a transaction hash, an agent name.',
        },
        size: {
          type: 'integer',
          description: 'Output size in pixels, 120–1200. Defaults to 600. Larger sheets are available from the REST endpoint, which streams the image rather than inlining it.',
          minimum: 120,
          maximum: MCP_MAX_SIZE,
        },
        pattern: {
          type: 'string',
          description: 'Force a traditional pattern. Omit and the seed chooses.',
          enum: PATTERN_NAMES,
        },
        palette: {
          type: 'string',
          description: 'Force a pigment palette. Omit and the seed chooses.',
          enum: PALETTE_NAMES,
        },
      },
      required: ['seed'],
    },
  },
  {
    name: 'wallet_portrait',
    description:
      'Read a wallet as a marbling bath: every transaction becomes a drop of paint, laid oldest first, so early activity thins into veins while recent activity sits on top. The pattern is chosen from how the account behaves. Returns a PNG image plus a legend naming every mark.',
    inputSchema: {
      type: 'object',
      properties: {
        address: { type: 'string', description: 'The account to read.' },
        block: {
          type: 'integer',
          description:
            'X Layer block height to pin the reading to. Omit and the current height is resolved, so the artwork stays reproducible.',
        },
        events: {
          type: 'array',
          description:
            'Optional transaction history. Supply it and no chain lookup happens — useful for agents that already hold the data.',
          items: {
            type: 'object',
            properties: {
              hash: { type: 'string' },
              ts: { type: 'integer', description: 'Unix seconds.' },
              value: { type: 'number' },
              token: { type: 'string' },
              counterparty: { type: 'string' },
            },
          },
        },
        size: { type: 'integer', description: 'Output size in pixels, 120–1200. Defaults to 600.' },
      },
      required: ['address'],
    },
  },
];

function clampSize(raw, fallback = 600) {
  const n = Number(raw);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(120, Math.min(MCP_MAX_SIZE, Math.round(n)));
}

/** MCP image content block. */
function imageContent(png) {
  return { type: 'image', data: png.toString('base64'), mimeType: 'image/png' };
}

async function callTool(name, args = {}, ctx) {
  if (name === 'marble') {
    const seed = args.seed;
    if (typeof seed !== 'string' || !seed.length) {
      return { isError: true, content: [{ type: 'text', text: 'seed is required — pass any string.' }] };
    }
    if (args.pattern && !PATTERN_NAMES.includes(args.pattern)) {
      return { isError: true, content: [{ type: 'text', text: `Unknown pattern "${args.pattern}". Choose one of: ${PATTERN_NAMES.join(', ')}` }] };
    }
    if (args.palette && !PALETTE_NAMES.includes(args.palette)) {
      return { isError: true, content: [{ type: 'text', text: `Unknown palette "${args.palette}". Choose one of: ${PALETTE_NAMES.join(', ')}` }] };
    }

    const size = clampSize(args.size);
    const key = `mcp|marble|${seed}|${size}|${args.pattern ?? ''}|${args.palette ?? ''}`;
    const hit = ctx?.cache?.get(key);
    if (hit) return hit;

    const { svg, meta } = render(seed, {
      width: 1000,
      height: 1000,
      pattern: args.pattern,
      palette: args.palette,
    });
    const result = {
      content: [
        imageContent(toPng(svg, { width: size })),
        {
          type: 'text',
          text: `${meta.patternLabel} · ${meta.paletteLabel}. Seed "${meta.seed}". Ask for this seed again and you get this exact sheet.`,
        },
      ],
    };
    ctx?.cache?.set(key, result);
    return result;
  }

  if (name === 'wallet_portrait') {
    const address = args.address;
    if (typeof address !== 'string' || !address.length) {
      return { isError: true, content: [{ type: 'text', text: 'address is required.' }] };
    }

    const events = Array.isArray(args.events) ? args.events : [];
    let block = Number.isFinite(args.block) ? args.block : null;
    let pinning = block != null ? 'supplied' : 'resolved';
    if (block == null) {
      block = await latestBlock('xlayer');
      if (block == null) pinning = 'unavailable';
    }

    const { svg, legend, meta } = renderReading(
      { address, chain: 'xlayer', block, events },
      { width: 1000, height: 1000 },
    );

    const lines = [
      `${meta.patternLabel} — ${meta.reason}`,
      pinning === 'unavailable'
        ? 'X Layer could not be reached, so this sheet is not pinned to a block.'
        : `Pinned to X Layer block ${block}.`,
      events.length
        ? `${legend.length} transactions, ${legend.length} drops of paint.`
        : 'No history supplied, so this is rendered from the address alone. Pass an events array to read the actual account.',
    ];
    for (const e of legend.slice(0, 12)) {
      lines.push(`  ${e.token} ${e.value} — holds ${(e.share * 100).toFixed(2)}% of the sheet`);
    }

    return {
      content: [imageContent(toPng(svg, { width: clampSize(args.size) })), { type: 'text', text: lines.join('\n') }],
    };
  }

  return { isError: true, content: [{ type: 'text', text: `Unknown tool "${name}".` }] };
}

/**
 * Handle one JSON-RPC message. Returns the reply object, or null for a
 * notification (which must be answered with 202 and no body).
 */
export async function handleRpc(msg, ctx) {
  const { id, method, params } = msg ?? {};
  const reply = (result) => ({ jsonrpc: '2.0', id, result });
  const fail = (code, message) => ({ jsonrpc: '2.0', id, error: { code, message } });

  // Notifications carry no id and expect no response.
  if (id === undefined || id === null) return null;

  switch (method) {
    case 'initialize': {
      const asked = params?.protocolVersion;
      return reply({
        protocolVersion: SUPPORTED_PROTOCOLS.includes(asked) ? asked : DEFAULT_PROTOCOL,
        capabilities: { tools: { listChanged: false } },
        serverInfo: SERVER_INFO,
      });
    }
    case 'ping':
      return reply({});
    case 'tools/list':
      return reply({ tools: TOOLS });
    case 'tools/call': {
      const toolName = params?.name;
      if (!toolName) return fail(-32602, 'params.name is required');
      try {
        return reply(await callTool(toolName, params?.arguments ?? {}, ctx));
      } catch (err) {
        console.error('[ebru:mcp]', err);
        return reply({ isError: true, content: [{ type: 'text', text: 'The bath failed to render.' }] });
      }
    }
    case 'resources/list':
      return reply({ resources: [] });
    case 'prompts/list':
      return reply({ prompts: [] });
    default:
      return fail(-32601, `Method not found: ${method}`);
  }
}

/**
 * Something POSTed here that is not a JSON-RPC message at all.
 *
 * The marketplace's own test harness is not something we can read, and the two
 * rejections we collected both said the same thing: no response, task timed
 * out. So the rule here is simple — never answer with nothing. If the body
 * carries arguments we recognise, do the work and return it. If it does not,
 * return the instructions for calling properly. Either way the caller gets a
 * body it can act on.
 */
export async function unrecognizedPost(body, ctx, url) {
  const obj = body && typeof body === 'object' ? body : {};

  // Tolerate a direct, non-protocol call: an agent that simply posts the
  // arguments should get its artwork rather than a lecture.
  const direct = obj.arguments && typeof obj.arguments === 'object' ? obj.arguments : obj;

  if (typeof direct.seed === 'string' && direct.seed.length) {
    const result = await callTool('marble', direct, ctx);
    return { ok: !result.isError, tool: 'marble', ...result };
  }
  if (typeof direct.address === 'string' && direct.address.length) {
    const result = await callTool('wallet_portrait', direct, ctx);
    return { ok: !result.isError, tool: 'wallet_portrait', ...result };
  }

  return {
    ok: false,
    error: 'Not a JSON-RPC message and no recognisable arguments.',
    protocol: 'mcp',
    transport: 'streamable-http',
    howToCall: {
      mcp: 'POST {"jsonrpc":"2.0","id":1,"method":"tools/list","params":{}} to this URL.',
      direct: 'Or POST {"seed":"any string"} to get an artwork, or {"address":"0x…"} for a wallet portrait.',
    },
    tools: TOOLS.map((t) => ({ name: t.name, required: t.inputSchema.required })),
    docs: url ? `${url.origin}/` : undefined,
  };
}

export const MCP_TOOLS = TOOLS;
export { SERVER_INFO };
